name: Terraform Validation

on:
  pull_request:
    branches: [ main, master, production ]
  push:
    branches: [ main, master, production ]

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      - run: terraform fmt -check
      - run: terraform init -backend=false
      - run: terraform validate
